{% set name = "colorlog" %}
{% set version = "6.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb4ae5cb65fe7fec7773c2306061a8e63e02efc2c72eba9d27b0fa23c94f1321

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools >=38.6.0
    - wheel
    - colorama  # [win]
  run:
    - python
    - colorama  # [win]

test:
  imports:
    - colorlog

about:
  home: https://github.com/borntyping/python-colorlog
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Log formatting with colors!
  description: Add colours to the output of Python's logging module.
  dev_url: https://github.com/borntyping/python-colorlog
  doc_url: https://github.com/borntyping/python-colorlog

extra:
  recipe-maintainers:
    - frol
    - forrestwaters
