{% set version = "6.4.1" %}

package:
  name: colorlog
  version: {{ version }}

source:
  fn: colorlog-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/c/colorlog/colorlog-{{ version }}.tar.gz
  sha256: af99440154a01f27c09256760ea3477982bf782721feaa345904e806879df4d8

build:
  number: 1
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools >=38.6.0
    - colorama  # [win]

  run:
    - python
    - colorama  # [win]

test:
  imports:
    - colorlog
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/borntyping/python-colorlog
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Log formatting with colors!
  dev_url: https://github.com/borntyping/python-colorlog

extra:
  recipe-maintainers:
    - frol
    - forrestwaters
