{% set version = "3.0.1" %}

package:
  name: colorlog
  version: {{ version }}

source:
  fn: colorlog-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/colorlog/colorlog-{{ version }}.tar.gz
  md5: 7d4c8a59c5df03f31fe939faccc970d1

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - colorama  # [win]

  run:
    - python
    - colorama  # [win]

test:
  imports:
    - colorlog

about:
  home: https://github.com/borntyping/python-colorlog
  license: MIT
  summary: Log formatting with colors!

extra:
  recipe-maintainers:
    - frol
    - borntyping
