travis:
  secure:
    BINSTAR_TOKEN: NHuFdYUIgQqYXuoHsiLeK+dBGAy/6ChNO3porfqjNPbNiMjwy6wII5EjFDBV2pRF4iunTLERNdKe2jk7jLhkAZw5PNc/fxP50+moCJAxrJ0szm/SznWOh8kMQHupZak2F8WPtEQmtL2An2HHrH7rd8eosGjwI6REuCj+TJFNLUMA0W4tFyHG7IV0g1QXwYkcBGeQCohI+cqrjzFveXYYDV1hUpPXj0AG+XsbHjW4Uwf0+c73tVVauUB3G91yH/wVUg+Ugu8g6ZeL0ExP/ZZfTvk51jB5+snG6Jnxc5OPjXZ+SrANx9u7nEPC3H+NJwJVyCOLVeMuy2BTHf5UebY5JZ3uR5ZUPAHqmQpEDFCsXXgutONZ1vJZxABQ22D7P0Wu0YtaZ6tRX7MkqFltE2Q64aP2sJBf6oembs2gqQ2PGOrjQ1Mw3AfvGfshQ4snAk15oXaOyJnniHOHBgRTlkzvwvaOiBndwAFVsE3NDYgIp5ndCEY1ByiDbTEBCjn4cSX3Bq6vbAmbpQyb6QGxGPUPv6Wqnl5hEgcSvyK47sLStHUgomg1e7clKnfNqBpqXSIlcjg98Ht1x+PtAa7ZXGt7ccPVb+fD5wUv51Lc9YsIq+izKR0H87DhcoTvUIYigsgO4mxkEkJWkWNzukeGjV8rEbhx2WQ9cjpkKJqCnMbEQSU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
