travis:
  secure:
    BINSTAR_TOKEN: JG8SvRVIpT1/8WsiZEq3aJFzYeoLR+IGy0dc/j2cKrUVsoAOon7t3aGtR/dgu9SdWffo0SVf8bDnRDZIi9fKF/4JJZ5e4iZlRFNSnR+Kd0prhUHQzKnJ0Bpm9Veu2663iAYY1gkDRG5EvgMqNKiYeOKwBA+5urXlM7cUkjelAvTNuDXBJ+R3a0eLFceUMlRYTepdHMO0GjJBBGOWvAfn53P08vQLZO9rHhqMZlIg9rSMrVINRZArq3dS/+v8DTVPSlG2/HU4LdwgCoovjlKAtdGTOC/XJAgyfZiX0Z59fPZlZmHL2kUKfm4y9Zjv/B4bx0BaBm3B1ih8YsArNbFbcoa16t+OUztwLVzJeiBJFP8/fZ+pwszJ1kyp2E4RL7j6rY3Z2gkYHK/bOiZVGsIPiZkxuD7GNISZqP3JFUkD9kQq0TPCvCXRsweOATfkxHF+HP834ozKjMDFZpPBGWK6UrNxK7HP2I+ziUjLMJxwfcQEVJBU6YBvfUoJ82oJy9ngFAEgbIF3cvUE+4Xr1ZuEq62RIpzZplujCaRdsQE28sBrfWfT3GnyoQgdoD0jv+/kt6xmNeARd6ZbY35dFpsfmzJnPFrI4CyLhdINUjQ4nyj+WOuaeuqqgWnp0IGJeSO+bsdDHSLgzaQlKZxGeGbKZ3ehk7P+dqE72l1jQGeHd/4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
