travis:
  secure:
    BINSTAR_TOKEN: f7vI26mlOzikWINjHhqCSGrbV57wXVJR14NYEBdfiwRr8ebk0rpl4M3L4C4HEf5tPCweZ8xX/5K9dB1DzrsXUKXrjiWpavA/rN/4CV+zPqQzGAMr7XtdFSNt6U7ZVTNrhSM4QfBAq/6ZlcSOZBN0W8AQ6MdhtqXh8znQ5KtAWpxeeLY0a4ZY7am37WasT8vQDtGlbAoQD1xqfyWY8nZ1kcAUu+s/mmsOmXuRwMDr7f6urkDyo/kbX6wwz/PFE0Bh+t64AvzptJ8hGKp4WclX/VacPwyy7ELkuMuSaCW//PAIM2SujW1s1ogUBKY8i/ME81fKpH1jfvpvyK4rBDx3E0ykcoGyVJ7Ji3N30Uf7yULp1pbBGd4n4ObRHDv5t/IFuFVmVfsNxOeHuzWJqV4bSkisfFXQ0c2lH6nIgKN93paLVRmmSL8UG1+ybtqGo+uen8r5QSXdGbk4lmyHjhzozJZUjtboIkeesl738oTxpUFSlu+llmtxRu6d4KlX7dPv5egY/GQIOZUtN2HOaOAg5w5VFRFn5Py6kdl4xar/eYCAoO/vKWDQ6B70gWFjHnQEGKmXL80WBx8TgiXztEJb1nxPxBVISmdVQg966tC9lmP+hqJwWFanlRZme2pXKaGwtO9ngiISIlsAZ0bM6bVBMq37rQw6Yf/3AokghjnjafI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
